
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-jenkins
  namespace: infra-jenkins 
  labels: 
    app: jenkins
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  # 可读可写，可被多个node挂载
  - ReadWriteMany
  # PVC删除时的回收策略: 保留
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-class
  local:
    path: /var/virtual-volumes/jenkins
  # 用于将local卷的pod调度到正确的位置
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        # 匹配结点标签值
        # 可通过 kubectl label node nodeName labelName=labelValue 设置标签
        # 可通过 kubectl get node --show-labels 查看标签
        # 可通过 kubectl label node nodename labelName- 删除标签
        - key: k8s.node.name
          # 匹配方式：In Exists
          operator: In
          values: 
          - master

